### ISSUE TITLE
Drop Favorited Items

### ISSUE THREAD

**Issue by accendium** [2Retr0/ItemFavorites#6]
By clicking the drop key and swapping to a different item slot at the same time, you can successfully drop a favorited item.

Video demonstration: https://www.youtube.com/watch?v=dYaxtIK4Jk0

**Comment by 2Retr0** [comment]
Thanks for posting! Fixed this in 1.0.5+1.20.1. My fix, however, only prevents favorited items from being dropped on the server-side. Seems like there is an ever-present issue of dropping items while simultaneously switching hotbar slots currently in the game (maybe caused by some race condition between swapping and dropping items on the server-side?)

Related: [MC-264632](https://bugs.mojang.com/browse/MC-264632)
